-- MySQL Script generated by MySQL Workbench
-- 03/27/16 11:04:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `idcargo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefono` (
  `idtelefono` INT NOT NULL,
  `movil` VARCHAR(45) NULL,
  `fijo` VARCHAR(45) NULL,
  PRIMARY KEY (`idtelefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gerenciagral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gerenciagral` (
  `idgerenciagral` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idgerenciagral`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gerencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gerencia` (
  `idgerencia` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `gerenciagral_idgerenciagral` INT NOT NULL,
  PRIMARY KEY (`idgerencia`),
  CONSTRAINT `fk_gerencia_gerenciagral1`
    FOREIGN KEY (`gerenciagral_idgerenciagral`)
    REFERENCES `mydb`.`gerenciagral` (`idgerenciagral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gerencia_gerenciagral1_idx` ON `mydb`.`gerencia` (`gerenciagral_idgerenciagral` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `idestado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipio` (
  `idmunicipio` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado_idestado` INT NOT NULL,
  PRIMARY KEY (`idmunicipio`),
  CONSTRAINT `fk_municipio_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `mydb`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_municipio_estado1_idx` ON `mydb`.`municipio` (`estado_idestado` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sector` (
  `idsector` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idsector`),
  CONSTRAINT `fk_sector_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `mydb`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sector_municipio1_idx` ON `mydb`.`sector` (`municipio_idmunicipio` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`coordinacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coordinacion` (
  `idcoordinacion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `gerencia_idgerencia` INT NOT NULL,
  `sector_idsector` INT NOT NULL,
  PRIMARY KEY (`idcoordinacion`),
  CONSTRAINT `fk_coordinacion_gerencia1`
    FOREIGN KEY (`gerencia_idgerencia`)
    REFERENCES `mydb`.`gerencia` (`idgerencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordinacion_sector1`
    FOREIGN KEY (`sector_idsector`)
    REFERENCES `mydb`.`sector` (`idsector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_coordinacion_gerencia1_idx` ON `mydb`.`coordinacion` (`gerencia_idgerencia` ASC);

CREATE INDEX `fk_coordinacion_sector1_idx` ON `mydb`.`coordinacion` (`sector_idsector` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Condicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Condicion` (
  `idCondicion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCondicion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `usuariosap` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contratista` VARCHAR(45) NULL,
  `duracion` VARCHAR(45) NULL,
  `cargo_idcargo` INT NOT NULL,
  `telefono_idtelefono` INT NOT NULL,
  `coordinacion_idcoordinacion` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `Condicion_idCondicion` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `fk_usuario_cargo`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `mydb`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_telefono1`
    FOREIGN KEY (`telefono_idtelefono`)
    REFERENCES `mydb`.`telefono` (`idtelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_coordinacion1`
    FOREIGN KEY (`coordinacion_idcoordinacion`)
    REFERENCES `mydb`.`coordinacion` (`idcoordinacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_Condicion1`
    FOREIGN KEY (`Condicion_idCondicion`)
    REFERENCES `mydb`.`Condicion` (`idCondicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_cargo_idx` ON `mydb`.`usuario` (`cargo_idcargo` ASC);

CREATE INDEX `fk_usuario_telefono1_idx` ON `mydb`.`usuario` (`telefono_idtelefono` ASC);

CREATE INDEX `fk_usuario_coordinacion1_idx` ON `mydb`.`usuario` (`coordinacion_idcoordinacion` ASC);

CREATE INDEX `fk_usuario_usuario1_idx` ON `mydb`.`usuario` (`usuario_idusuario` ASC);

CREATE INDEX `fk_usuario_Condicion1_idx` ON `mydb`.`usuario` (`Condicion_idCondicion` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`tiposervicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tiposervicio` (
  `idtiposervicio` INT NOT NULL,
  PRIMARY KEY (`idtiposervicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mainframe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mainframe` (
  `idmainframe` INT NOT NULL,
  `tiposervicio_idtiposervicio` INT NOT NULL,
  PRIMARY KEY (`idmainframe`),
  CONSTRAINT `fk_mainframe_tiposervicio1`
    FOREIGN KEY (`tiposervicio_idtiposervicio`)
    REFERENCES `mydb`.`tiposervicio` (`idtiposervicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_mainframe_tiposervicio1_idx` ON `mydb`.`mainframe` (`tiposervicio_idtiposervicio` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`netwin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`netwin` (
  `idnetwin` INT NOT NULL,
  PRIMARY KEY (`idnetwin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servcon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servcon` (
  `idservcon` INT NOT NULL,
  PRIMARY KEY (`idservcon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `idroles` INT NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`planilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planilla` (
  `idplantilla` INT NOT NULL,
  `fecha` DATE NULL,
  `justificacion` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  `mainframe_idmainframe` INT NOT NULL,
  `netwin_idnetwin` INT NOT NULL,
  `servcro_idservcon` INT NOT NULL,
  `roles_idroles` INT NOT NULL,
  PRIMARY KEY (`idplantilla`),
  CONSTRAINT `fk_planilla_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planilla_mainframe1`
    FOREIGN KEY (`mainframe_idmainframe`)
    REFERENCES `mydb`.`mainframe` (`idmainframe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planilla_netwin1`
    FOREIGN KEY (`netwin_idnetwin`)
    REFERENCES `mydb`.`netwin` (`idnetwin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planilla_servcro1`
    FOREIGN KEY (`servcro_idservcon`)
    REFERENCES `mydb`.`servcon` (`idservcon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planilla_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `mydb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_planilla_usuario1_idx` ON `mydb`.`planilla` (`usuario_idusuario` ASC);

CREATE INDEX `fk_planilla_mainframe1_idx` ON `mydb`.`planilla` (`mainframe_idmainframe` ASC);

CREATE INDEX `fk_planilla_netwin1_idx` ON `mydb`.`planilla` (`netwin_idnetwin` ASC);

CREATE INDEX `fk_planilla_servcro1_idx` ON `mydb`.`planilla` (`servcro_idservcon` ASC);

CREATE INDEX `fk_planilla_roles1_idx` ON `mydb`.`planilla` (`roles_idroles` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
